#!/usr/bin/env python3
"""Apply Atlas product-version metadata without changing Chromium internals."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


SEMVER = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z.-]+))?$")
RC_VERSION_FILES = (
    "chrome/app/chrome_version.rc.version",
    "chrome/installer/gcapi/gcapi_dll_version.rc.version",
    "chrome/installer/mini_installer/mini_installer_exe_version.rc.version",
    "chrome/installer/setup/setup_exe_version.rc.version",
)


def read_manifest(path: Path) -> tuple[str, str, str]:
    manifest = json.loads(path.read_text(encoding="utf-8"))
    version = manifest["version"]
    match = SEMVER.fullmatch(version)
    if not match:
        raise ValueError(f"Atlas version must use SemVer (for example 0.1.0): {version}")
    return version, manifest["channel"], manifest["chromium"]["version"]


def write_header(checkout: Path, version: str, channel: str, engine: str) -> None:
    header = checkout / "chrome/common/atlas_version.h"
    content = f"""// Generated by tools/chromium/apply-version.py. Do not edit.
#ifndef CHROME_COMMON_ATLAS_VERSION_H_
#define CHROME_COMMON_ATLAS_VERSION_H_

#define ATLAS_VERSION_STRING \"{version}\"
#define ATLAS_VERSION_STRING_U16 u\"{version}\"
#define ATLAS_CHANNEL_STRING \"{channel}\"
#define ATLAS_CHROMIUM_VERSION_STRING \"{engine}\"

#endif  // CHROME_COMMON_ATLAS_VERSION_H_
"""
    header.write_bytes(content.encode("utf-8"))


def update_windows_metadata(checkout: Path, version: str) -> None:
    match = SEMVER.fullmatch(version)
    assert match
    numeric_version = ",".join((*match.groups()[:3], "0"))

    for relative_path in RC_VERSION_FILES:
        path = checkout / relative_path
        content = path.read_bytes().decode("utf-8")
        content, numeric_count = re.subn(
            r"(?m)^(\s*)PRODUCTVERSION\s+.*$",
            rf"\1PRODUCTVERSION {numeric_version}",
            content,
            count=1,
        )
        content, string_count = re.subn(
            r'(?m)^(\s*VALUE "ProductVersion", )"[^"]*"$',
            rf'\1"{version}"',
            content,
            count=1,
        )
        if numeric_count != 1 or string_count != 1:
            raise RuntimeError(f"ProductVersion fields not found in {relative_path}")
        path.write_bytes(content.encode("utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("checkout", type=Path, help="Path to the Chromium src checkout")
    parser.add_argument("manifest", type=Path, help="Path to atlas-version.json")
    args = parser.parse_args()

    checkout = args.checkout.resolve()
    version, channel, engine = read_manifest(args.manifest.resolve())

    write_header(checkout, version, channel, engine)
    update_windows_metadata(checkout, version)
    print(f"Applied Atlas {version} ({channel}); Chromium engine remains {engine}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
